### ISSUE TITLE
HW5: Persistance

### ISSUE THREAD

**Issue by MattyAyOh** [drwecker/StockPrices#11]
- Persist stock entries across app launches
- Add button and functionality to export stock entries
- Add button and functionality to import stock entries

Due **August 26th, 11:59PM**

**50 Points**

**Comment by MattyAyOh** [comment]
@drwecker

**Comment by drwecker** [comment]
It's looking pretty amazing in there.  Hopefully the design is just really impressive to you.

**Comment by MattyAyOh** [comment]
**50/50**
nice job

You should check your commits though, there is a lot of random junk that shouldn't be committed, or ignored
