### ISSUE TITLE
HW1: Get some stock data

### ISSUE THREAD

**Issue by MattyAyOh** [drwecker/StockPrices#2]
Form an HTTP GET request, parse the response, and display some data from a stock API

15 Points

**Due July 29th, 11:59PM**

**Comment by MattyAyOh** [comment]
@drwecker

**Comment by drwecker** [comment]
That's a good idea, thanks!

**Comment by drwecker** [comment]
@MattyAyOh I think the assignment is more or less complete.  I didn't think I'd get it in the 2 hour timeframe I had to work on it, but barely got it all working.  The stock name is hardcoded for now, but it is calling the yahoo finance API and getting the actual price from the web.

**Comment by drwecker** [comment]
Kinda funny, I went in trying to use the Google Finance API originally, but it was deprecated a few years ago and no longer exists it seems.

**Comment by MattyAyOh** [comment]
Looks good, meets all specs. 15/15

**Comment by MattyAyOh** [comment]
Cutting it real close, eh?
![lol](https://cloud.githubusercontent.com/assets/5342037/17271292/4cbbbe10-5645-11e6-93d0-7aaf7cd9794d.PNG)
