### ISSUE TITLE
HW2: Allow user input

### ISSUE THREAD

**Issue by MattyAyOh** [drwecker/StockPrices#7]
Directly related to #4 

Add a text field that takes user input for a ticker, and updates the price accordingly

Also handle potential failures that may occur with network requests

20 points total.  Due August 5th, 11:59 PM

**Comment by MattyAyOh** [comment]
@drwecker making sure you saw this

**Comment by drwecker** [comment]
Looks pretty good for the basic ability to pick any ticker symbol you want and covering the basic error handling cases for HTTP requests and invalid ticker symbols.

**Comment by MattyAyOh** [comment]
I see your error messages, bro

Looks good, 20/20
