### ISSUE TITLE
HW3: Pretty 'er up

### ISSUE THREAD

**Issue by MattyAyOh** [drwecker/StockPrices#9]
Let's apply some logical UX here

- Make a table with columns for Ticker and Price
- Every time a ticker is searched, add it to a table instead of replacing it 
- Make the text field and submit button prettier
- Throw in a help button in a bottom corner, when pressed displays a popup with some help information

_**30 points**_

**Due August 12th at 11:59PM**

**Comment by MattyAyOh** [comment]
@drwecker

**Comment by drwecker** [comment]
Grr, definitely hitting a wall on this one.  I might need to learn significantly more about data binding and WPF to figure out how to piece it together.

**Comment by drwecker** [comment]
FYI my Friday night turned into Saturday plans so I'll take a look at this Sunday.  I guess I'm at the mercy of your kindness on how many points I lose :)

**Comment by MattyAyOh** [comment]
Get it done by 8PM tomorrow (monday) and depending on quality we'll see

**Comment by drwecker** [comment]
Haha, ok :)
It has some room for improvement, but the formatting type UI styling looks like a bigger effort than I'm going to be able to get in for this round.  On to the next!

**Comment by MattyAyOh** [comment]
Core functionality is there, visually pretty minimal. but code looks pretty clean.

11/30 points
